name = "The Merge Season 2"
author = "nate601"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f8c0d7a0233946b4d18095b7e3de47b7e99b0a174ea0e39d72a86acbed07b72"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
